version: '2.2'

services:
    webserver:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        environment:
            - VIRTUAL_PORT=80
        ports:
            - "8081:80"
            - "443:443"
        volumes:
            - ./:/var/www
    app:
        build:
            context: ./
            dockerfile: docker/app/DockerFile
        volumes:
            - ./:/var/www
        environment:
            - DB_PORT=3306
            - DB_HOST=127.0.0.1
    db:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=123456789
            - MYSQL_DATABASE=test
        ports:
            -   "33061:3306"
